dist: trusty
language: node_js
cache:
  directories:
  - node_modules
node_js:
- '8'
before_script:
- npm install -g httpserver
- npm run build
- cd dist && httpserver -p 8080 &
script:
- npx cypress run
deploy:
  provider: surge
  skip_cleanup: true
  domain: shoppingvue.surge.sh
  project: ./dist
  on:
    branch: master
